# Databricks notebook source

# COMMAND ----------

# MAGIC %md
# MAGIC # 01 — Catalog Setup
# MAGIC
# MAGIC Creates the Unity Catalog **catalog**, all **schemas**, and a **managed volume**.
# MAGIC Applies catalog-level and schema-level **tags** and **descriptions**.
# MAGIC
# MAGIC Safe to re-run — uses `IF NOT EXISTS` throughout unless `reset_catalog = true`.

# COMMAND ----------

dbutils.widgets.text("catalog_name",           "sample_db", "Catalog Name")
dbutils.widgets.text("catalog_managed_location", "",        "Catalog managed location (optional)")
dbutils.widgets.text("env",           "dev",        "Environment")
dbutils.widgets.text("reset_catalog", "false",      "Drop & Recreate (true/false)")
dbutils.widgets.text("num_customers", "2000",       "Num Customers")
dbutils.widgets.text("num_orders",    "50000",      "Num Orders")

CATALOG = dbutils.widgets.get("catalog_name")
MANAGED_LOCATION = dbutils.widgets.get("catalog_managed_location").strip()
ENV     = dbutils.widgets.get("env")
RESET   = dbutils.widgets.get("reset_catalog").strip().lower() == "true"

loc_msg = f"  |  Managed location: {MANAGED_LOCATION}" if MANAGED_LOCATION else ""
print(f"Catalog: {CATALOG}  |  Env: {ENV}  |  Reset: {RESET}{loc_msg}")

# COMMAND ----------

# MAGIC %md ### Reset (optional)

# COMMAND ----------

if RESET:
    print(f"⚠  Dropping catalog '{CATALOG}' and all contents …")
    spark.sql(f"DROP CATALOG IF EXISTS {CATALOG} CASCADE")
    print(f"   Catalog '{CATALOG}' dropped.")

# COMMAND ----------

# MAGIC %md ### Create Catalog
# MAGIC
# MAGIC If the metastore has no default storage root, set **Catalog managed location** (e.g. `abfss://container@account.dfs.core.windows.net/path` or `s3://bucket/prefix`) so `CREATE CATALOG` can succeed.

# COMMAND ----------

_catalog_comment = """Northwind Analytics — sample retail database for Databricks demos.
Showcases Unity Catalog governance, Genie (AI/BI), lineage, tags, PII masking, and ML model registration.
Generated by the databricks-schema-maker utility."""

_comment_sql = _catalog_comment.replace("'", "''")

if MANAGED_LOCATION:
    _loc_sql = MANAGED_LOCATION.replace("'", "''")
    spark.sql(f"""
        CREATE CATALOG IF NOT EXISTS {CATALOG}
        MANAGED LOCATION '{_loc_sql}'
        COMMENT '{_comment_sql}'
    """)
else:
    spark.sql(f"""
        CREATE CATALOG IF NOT EXISTS {CATALOG}
        COMMENT '{_comment_sql}'
    """)

spark.sql(f"""
    ALTER CATALOG {CATALOG} SET TAGS (
        'env'         = '{ENV}',
        'purpose'     = 'demo',
        'domain'      = 'retail',
        'owner'       = 'data_engineering',
        'cost_centre' = 'shared_services',
        'pii'         = 'true'
    )
""")

print(f"Catalog '{CATALOG}' created.")

# COMMAND ----------

# MAGIC %md ### Create Schemas

# COMMAND ----------

SCHEMAS = {
    "dimensions": {
        "comment": "Master dimension tables containing slowly-changing attributes. "
                   "Includes customer, product, store, employee, date, and promotion dimensions.",
        "tags": {
            "domain":          "master_data",
            "data_tier":       "gold",
            "classification":  "internal",
            "pii":             "true",
            "refresh_cadence": "daily",
        },
    },
    "facts": {
        "comment": "Transactional fact tables. Append-heavy high-volume tables "
                   "covering orders, inventory snapshots, and returns.",
        "tags": {
            "domain":          "transactions",
            "data_tier":       "gold",
            "classification":  "confidential",
            "pii":             "false",
            "refresh_cadence": "hourly",
        },
    },
    "mart": {
        "comment": "Business-facing analytical views and pre-aggregated tables. "
                   "Optimised for Genie (AI/BI) and self-service BI tools. "
                   "All objects have comprehensive column descriptions.",
        "tags": {
            "domain":          "analytics",
            "data_tier":       "gold",
            "classification":  "internal",
            "genie_enabled":   "true",
            "refresh_cadence": "daily",
        },
    },
    "ml": {
        "comment": "Machine learning feature engineering tables and registered models. "
                   "Contains pre-computed customer and product features used for "
                   "churn prediction and demand forecasting.",
        "tags": {
            "domain":          "machine_learning",
            "data_tier":       "gold",
            "classification":  "internal",
            "refresh_cadence": "weekly",
        },
    },
    "raw": {
        "comment": "Raw ingestion landing zone. Managed volume for CSV/JSON file uploads "
                   "before transformation into the dimensions and facts schemas.",
        "tags": {
            "domain":          "ingestion",
            "data_tier":       "bronze",
            "classification":  "internal",
            "refresh_cadence": "ad_hoc",
        },
    },
}

for schema_name, meta in SCHEMAS.items():
    comment = meta["comment"].replace("'", "\\'")
    spark.sql(f"""
        CREATE SCHEMA IF NOT EXISTS {CATALOG}.{schema_name}
        COMMENT '{comment}'
    """)

    tag_pairs = ", ".join(f"'{k}' = '{v}'" for k, v in meta["tags"].items())
    spark.sql(f"ALTER SCHEMA {CATALOG}.{schema_name} SET TAGS ({tag_pairs})")
    print(f"  Schema '{schema_name}' created with {len(meta['tags'])} tags.")

print(f"\n{len(SCHEMAS)} schemas created in catalog '{CATALOG}'.")

# COMMAND ----------

# MAGIC %md ### Create Managed Volume

# COMMAND ----------

spark.sql(f"""
    CREATE VOLUME IF NOT EXISTS {CATALOG}.raw.raw_uploads
    COMMENT 'Managed volume for raw file ingestion. Drop CSV, JSON, or Parquet files here.
Files in this volume are processed by ingestion pipelines and loaded into the dimensions and facts schemas.
Unity Catalog manages the underlying storage path automatically.'
""")

spark.sql(f"""
    ALTER VOLUME {CATALOG}.raw.raw_uploads
    SET TAGS ('domain' = 'ingestion', 'data_tier' = 'bronze', 'managed' = 'true')
""")

print("Managed volume 'raw_uploads' created.")

# COMMAND ----------

# Write sample seed files to the volume so it is not empty
import pandas as pd

sample_products_pdf = pd.DataFrame({
    "product_id": ["PROD-EXT-001", "PROD-EXT-002", "PROD-EXT-003"],
    "product_name": ["Wireless Keyboard", "USB-C Hub", "Webcam HD 1080p"],
    "category": ["Electronics", "Electronics", "Electronics"],
    "unit_price": [79.99, 49.99, 89.99],
    "supplier_id": ["SUP-001", "SUP-002", "SUP-001"],
})

sample_events_pdf = pd.DataFrame({
    "event_id": ["EVT-001", "EVT-002", "EVT-003"],
    "event_type": ["page_view", "add_to_cart", "purchase"],
    "customer_id": ["CUST-001234", "CUST-005678", "CUST-009012"],
    "timestamp": ["2024-11-01 10:32:45", "2024-11-01 10:33:02", "2024-11-01 10:38:17"],
    "product_id": ["PROD-001", "PROD-001", "PROD-001"],
})

vol_path = f"/Volumes/{CATALOG}/raw/raw_uploads"

(spark.createDataFrame(sample_products_pdf)
      .coalesce(1)
      .write.mode("overwrite")
      .option("header", "true")
      .csv(f"{vol_path}/seed_products/"))

(spark.createDataFrame(sample_events_pdf)
      .coalesce(1)
      .write.mode("overwrite")
      .option("header", "true")
      .csv(f"{vol_path}/seed_events/"))

print(f"Sample seed files written to {vol_path}")
print(f"  • seed_products/ — 3 sample product records")
print(f"  • seed_events/   — 3 sample web event records")

# COMMAND ----------

# MAGIC %md ### Summary

# COMMAND ----------

summary = spark.sql(f"""
    SELECT
        catalog_name,
        schema_name,
        NULL AS object_count
    FROM system.information_schema.schemata
    WHERE catalog_name = '{CATALOG}'
    ORDER BY schema_name
""")

display(summary)
print(f"\nCatalog '{CATALOG}' is ready. Proceeding to dimension table creation.")
